language: java

jdk: -openjdk8 

addons:
  sonarcloud:
    organization: "pippopaperino"
    token:
      secure: "xxcMHRLZJVMQ4tI5KpqjrenGKHYpNSXuYj3i8Mh/KcIKBDY4rXU9aapKOnxwoHbCXs/NdDYN+p/kYKP32qTIAYGxdlP7+TauH53MXN3mc6ZuIYY1G13BLXEkbX5tlDrmm8/PFpFd5F4Z0J8AINqeHKP8iPG72FwGoj3PXgK4EVv1ylgFIGwTrJkrnxsaEWgY3yte3Ql2zPlw3MsI37Qzt5JRAY0u5HdCCdC+FwsBpxs3F+Jk4PpOKx+ZOmYJkeZlwUkqxSvvLOP7oiuRmyvluNW8VURarjfkQl0FY4BTyG/uGfzU4eNBeUoWX1JKZbuQKEayyvaDnkBijbn5XjDFD/ydSvpK1At7OP1XP4pc8pg1NxW0CVERG/lYomONdgXVoN3xI0Tjj++4tV2eywT74uRmBi7rJRBpEFL74iQSxKbXmNwk0MnjHdgZEF8jH6sI8d7e7MLjzhmR4ORMIAEA1eNnZ5/0rhIsKw1DeTht10Qpa1E/0ghPlmczATLErm7KvQQfEw5VxPvaPktazsk1E37sydWgHeWAnz2xf+7bxpBQLJE050X1os60OxNfHIbgSQw7gNNLnwriU9eH9fQpNwaHKhTgd7+ivmcVg31JXD1dOarrLze4s29mGW4ZWfK633s+OcUoxaIJlfcHiNUkAKN9mH71fmDOGQf9RpdAi+g="
script:
  -ant build
script:
  - sonar-scanner
