language: java

jdk: -openjdk12

addons:
  sonarcloud:
    organization: "pippopaperino"
    token:
     secure: "Eckx4QmqtJc2QfEKq2iho94Obnq1aJvdFwnMYgmoKPep5G/21Qyvc5wAuGqNj6OXsl2X0q7F6L7R/qWdl40SvOWQ+9V/Cc7JzYPcUApzkjvYMG9fbOnei6QVQvcNH/STJYUetdkP72YLDj3Hh7Tsqonb/lBqqlXWOxWBugjzO5KpT3q/piH+Hor44IhrVbwzylR74kS7C8c21w+BPlFIAZHebQdSrNyWW7C7qEy+i4i8iuRIPowxuXkpVyFbNbHU/xJUTcY3FAVpoEglxQo4YASGnHR946AFt/bVbtyLaSDP37QCep3dut4+JoABvssSM8cOnU1oENZI9xQrZjTxvIqnIdRiHajZvxp6AvnaPD52cxwZrxj2mtpd2/PfKGw4y1sCnrisZoyR15kjgxp8PUGPLJLAlLdZ9Swd0+AXs/GL53R8BpXheEGBuXZPr/B6tDdmnVAp44bIyxinK2hhf/Rf+dqwmppd/4UIfP0fsZkQAjCLqAmWzMQMUzRravWQCbW1r31CXzyJQCjKEWFI2vzFyr/5evI2g/4b3jGSVw+jzvzaFMdBNuMr8Tb2sXzYbWkXEbAm34ktIZUbfcXOnKLT4rVPhZz1+gMEOz18xQfGiXHnUDLYCO6F4/qdGOkNKtL1poRVJsTKMxKpGwiOIXjBN67XrzLwxoy53CHxRP4="
script:
  -ant build
script:
  - sonar-scanner
